/* Page order for the deck. deck.js reads this for prev/next navigation
   and the "N / M" counter. Add new pages here, in presentation order.
   (01-qkt-matmul.html is the engine template page, kept out of the flow.) */
window.DECK_PAGES = [
  "01-pricing.html",
  "02-bottlenecks.html",
  "03-roofline.html",
  "04-phases.html",
  "05-anatomy.html",
  "06-on2.html",
  "07-flash.html",
  "08-kv.html",
  "09a-evo-map.html",
  "10a-gqa.html",
  "11a-mla.html",
  "12a-sparse.html",
  "13a-linear.html",
  "14a-kda.html",
  "15a-payoff.html",
  "09b-evo-map.html",
  "10b-gqa.html",
  "11b-mla.html",
  "12b-sparse.html",
  "13b-linear.html",
  "14b-kda.html",
  "15b-payoff.html",
  "09c-evo-map.html",
  "10c-gqa.html",
  "11c-mla.html",
  "12c-sparse.html",
  "13c-linear.html",
  "14c-kda.html",
  "15c-payoff.html",
  "09d-evo-map.html",
  "10d-gqa.html",
  "11d-mla.html",
  "12d-sparse.html",
  "13d-linear.html",
  "14d-kda.html",
  "15d-payoff.html",
  "09e-evo-map.html",
  "10e-gqa.html",
  "11e-mla.html",
  "12e-sparse.html",
  "13e-linear.html",
  "14e-kda.html",
  "15e-payoff.html",
];
